In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

### Creat tensors with tf.constant()

In [2]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [3]:
# Vektör oluşturma
vector = tf.constant([10, 10])
print(vector)
print(vector.ndim) #Vektörün boyutu

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [4]:
# Matrix oluşturma
matrix = tf.constant([[10, 7],
                     [7, 10]])

print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


In [5]:
# Tensor oluşturma
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
3


### Creat tensors with tf.variable()

In [6]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [7]:
changeable_tensor[0] = 9

TypeError: 'ResourceVariable' object does not support item assignment

In [8]:
changeable_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7])>

In [9]:
unchangeable_tensor[0].assign(9)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creat two random (but the same) tensors

In [10]:
random_1 = tf.random.Generator.from_seed(42) # Bu, belirli bir başlangıç değeri (seed) kullanarak bir rastgele sayı üreteci oluşturmanızı sağlar. Başlangıç değeri, aynı başlangıç değerini kullanan durumlarda bile tekrarlanabilir sonuçlar elde etmenizi sağlar. Eğer aynı başlangıç değerini verirseniz, üretilen rastgele sayılar aynı olacaktır. Bu örnekte, başlangıç değeri olarak 42 kullanılmış.
random_1 = random_1.normal(shape=(3, 2))
print(random_1)

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
print(random_2)

# Eşitler mi?
random_1 == random_2 #True

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Tensor deki ögelerin sıralarını karıştırma

In [11]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

shuffled = tf.random.shuffle(not_shuffled, seed=10)
print(shuffled)

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


**Exercise:** Write 5 random tensors and shuffle them  

In [12]:
tensor1 = tf.random.uniform(shape=(3, 4)) # uniform olması eşit aralıklarla rastgele sayılar üretir
tensor2 = tf.random.normal(shape=(3, 4)) # aralıkları tamamen rastgele olan sayılar üretir
tensor3 = tf.random.uniform(shape=(3, 4))
tensor4 = tf.random.normal(shape=(3, 4))
tensor5 = tf.random.uniform(shape=(3, 4))

tensors_to_shuffle = [tensor1, tensor2, tensor3, tensor4, tensor5]
shuffled_tensors = tf.random.shuffle(tensors_to_shuffle)

print(shuffled_tensors)

tf.Tensor(
[[[ 0.07487498 -0.7550695  -0.03832366 -1.0670892 ]
  [-0.62793756 -0.631967    0.44106978  0.95002836]
  [ 1.7634549   0.24905711 -1.9541459   1.1949075 ]]

 [[ 0.46439964  2.6252646  -0.73785836  0.47776106]
  [-1.3361545  -0.04507286 -1.5074811  -0.37169048]
  [ 1.2457341   0.37468094 -1.5002545  -0.56355387]]

 [[ 0.03452039  0.8649012   0.42233908  0.6068026 ]
  [ 0.39116836  0.30241597  0.9103581   0.60433996]
  [ 0.8759457   0.9828081   0.8872286   0.37400806]]

 [[ 0.9630227   0.02081776  0.17390776  0.4517945 ]
  [ 0.12394452  0.9529494   0.45991433  0.8429078 ]
  [ 0.21090269  0.7726337   0.6636554   0.97207236]]

 [[ 0.7720417   0.26249492  0.09034479  0.3158425 ]
  [ 0.2977147   0.23201895  0.24740744  0.01231241]
  [ 0.91350305  0.8175709   0.69252276  0.570261  ]]], shape=(5, 3, 4), dtype=float32)


### NumPy array'lerini tensor'a çevirme

In [13]:
numpy_A = np.arange(1, 25, dtype=np.int32) # 24 eleman var [1,24] 
print(numpy_A)

A = tf.constant(numpy_A, shape=(2, 3, 4)) # 2 * 3 * 4 = 24
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


In [14]:
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [15]:
print("Shape of tensor:", rank_4_tensor.shape)
print("Number of dimension (rank):", rank_4_tensor.ndim)
print("Total number of elements in tensor:", tf.size(rank_4_tensor)) # 2 * 3 * 4 * 5 = 120
print("Datatype of every element:", rank_4_tensor.dtype)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along  the last axis:", rank_4_tensor.shape[-1])

Shape of tensor: (2, 3, 4, 5)
Number of dimension (rank): 4
Total number of elements in tensor: tf.Tensor(120, shape=(), dtype=int32)
Datatype of every element: <dtype: 'float32'>
Elements along the 0 axis: 2
Elements along  the last axis: 5


### Indexing tensors

In [16]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [17]:
# Tensor'a boyut eklemek

rank_2_tensor = tf.constant([[1, 2],
                            [3, 4]])

rank_3_tensor = rank_2_tensor[..., tf.newaxis] # ... -> önceki bütün boyutları kabul et ve newaxis ile yeni boyut ekle
print(rank_3_tensor)

tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


In [18]:
# Başka bir alternatif
rank_3_tensor_alternatif =  tf.expand_dims(rank_2_tensor, axis=-1) # -1 çünkü son axis'e ekleyecek
print(rank_3_tensor_alternatif)

tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


### Manipulating tensors

In [19]:
tensor = tf.constant([[1, 2],
                      [3, 4]])
print(tensor + 10)
print(tensor * 2)
print(tf.multiply(tensor, 10))
print(tensor - 10)

tf.Tensor(
[[11 12]
 [13 14]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-9 -8]
 [-7 -6]], shape=(2, 2), dtype=int32)


### Matrix Multiplication

In [20]:
print(tensor, tensor)
print(tensor * tensor)
#matmul ve multiply farklı şeyler
print(tf.matmul(tensor, tensor))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


### Changing the datatype of a tensor 

In [26]:
# change from float32 to int16

B = tf.constant([1,3, 2.4])
print(B.dtype) # float32
C = tf.constant([1, 4])
print(C.dtype) #int32

D = tf.cast(B, dtype=tf.int16)
print(D.dtype)

<dtype: 'float32'>
<dtype: 'int32'>
<dtype: 'int16'>


### Aggregating tensors

In [30]:
# Mutlak değer alma
D = tf.constant([-7, -1])
print(D)

E = tf.abs(D) # Mutlak değer alma
print(E)

tf.Tensor([-7 -1], shape=(2,), dtype=int32)
tf.Tensor([7 1], shape=(2,), dtype=int32)


In [31]:
# Create a random tensor 0-100 size:50
E = tf.constant(np.random.randint(0, 100, size=50))
print(E)

tf.Tensor(
[44  2 23 78 64 71 92 14  6 21 84 32 33 31 53 33 42 22 32 53 90 29 20 26
 27 38 81 94 78 63 63 79 65 54 66 12 86 13 16 14 26 67 17 92 69 49 33 42
 49 82], shape=(50,), dtype=int32)


In [42]:
# min değeri bulma
print(tf.reduce_min(E))

# max değeri bulma
print(tf.reduce_max(E))

# toplamını bulma
print(tf.reduce_sum(E))

# Varyans ve standart sapma hesaplarken tensor'un float tipinde olması gerekiyor
# Bu yüzden önce float tipine çevirmemiz lazım

# varyans bulma
new_E = tf.cast(E, dtype=tf.float32)
varyans = tf.math.reduce_variance(new_E)
print(varyans)

# Standart sapma bulma
print(tf.math.sqrt(varyans)) # Standart sapma varyansın kareköküdür

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(94, shape=(), dtype=int32)
tf.Tensor(2370, shape=(), dtype=int32)
tf.Tensor(703.28, shape=(), dtype=float32)
tf.Tensor(26.519428, shape=(), dtype=float32)


### Find the positional max and min

In [45]:
F = tf.random.uniform(shape=[50], seed=42)
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.95227146, 0.67740774, 0.79531825, 0.75578177, 0.4759556 ,
       0.6310148 , 0.18602037, 0.11430776, 0.3362218 , 0.723335  ,
       0.21919966, 0.8573376 , 0.82392037, 0.59541273, 0.00296271,
       0.24725473, 0.5060741 , 0.36158872, 0.04483843, 0.97216606,
       0.82838845, 0.41458404, 0.601666  , 0.33958685, 0.5731027 ,
       0.23625553, 0.67478454, 0.00732017, 0.02091265, 0.9618796 ,
       0.6345031 , 0.22629452, 0.651536  , 0.8670281 , 0.25453997,
       0.27258146, 0.4647777 , 0.29214978, 0.21008277, 0.42609882,
       0.93323886, 0.4174106 , 0.7148676 , 0.5662477 , 0.30075896,
       0.8497542 , 0.45311093, 0.00433195, 0.09081542, 0.28513503],
      dtype=float32)>

In [50]:
# Find positional max
print(tf.argmax(F)) # index değerini verir
print(F[19])
print(F[tf.argmax(F)])

# kontrol edelim
print(F[19] == F[tf.argmax(F)]) #True

tf.Tensor(19, shape=(), dtype=int64)
tf.Tensor(0.97216606, shape=(), dtype=float32)
tf.Tensor(0.97216606, shape=(), dtype=float32)
tf.Tensor(True, shape=(), dtype=bool)


In [52]:
# Find positional min
print(tf.argmin(F)) # index değerini verir
print(F[14])
print(F[tf.argmin(F)])

# kontrol edelim
print(F[14] == F[tf.argmin(F)]) #True

tf.Tensor(14, shape=(), dtype=int64)
tf.Tensor(0.0029627085, shape=(), dtype=float32)
tf.Tensor(0.0029627085, shape=(), dtype=float32)
tf.Tensor(True, shape=(), dtype=bool)


### Squeezing a tensor (removing all single dimensions)

In [53]:
G = tf.constant(tf.random.uniform(shape=[50], seed=42), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.13859022, 0.677364  , 0.57776976, 0.6769707 , 0.85529864,
           0.26307547, 0.16501617, 0.42464197, 0.56730914, 0.3437599 ,
           0.44374728, 0.11031771, 0.53476083, 0.05655551, 0.8946748 ,
           0.6490574 , 0.6352521 , 0.24645054, 0.67025137, 0.904937  ,
           0.6629704 , 0.6767161 , 0.5502415 , 0.38707435, 0.50407314,
           0.95736146, 0.6753317 , 0.9438201 , 0.14085579, 0.15945208,
           0.87157416, 0.29930174, 0.01602423, 0.54037833, 0.6520896 ,
           0.87387013, 0.10270858, 0.86105835, 0.12225938, 0.20637023,
           0.93473125, 0.4714148 , 0.6826582 , 0.57907426, 0.63363206,
           0.4832946 , 0.5214349 , 0.18398428, 0.5597439 , 0.73508775]]]]],
      dtype=float32)>

In [54]:
G_squeezed = tf.squeeze(G) # tensor içindeki bütün tek boyutları siliyor
print(G_squeezed)
print(G_squeezed.shape)

tf.Tensor(
[0.13859022 0.677364   0.57776976 0.6769707  0.85529864 0.26307547
 0.16501617 0.42464197 0.56730914 0.3437599  0.44374728 0.11031771
 0.53476083 0.05655551 0.8946748  0.6490574  0.6352521  0.24645054
 0.67025137 0.904937   0.6629704  0.6767161  0.5502415  0.38707435
 0.50407314 0.95736146 0.6753317  0.9438201  0.14085579 0.15945208
 0.87157416 0.29930174 0.01602423 0.54037833 0.6520896  0.87387013
 0.10270858 0.86105835 0.12225938 0.20637023 0.93473125 0.4714148
 0.6826582  0.57907426 0.63363206 0.4832946  0.5214349  0.18398428
 0.5597439  0.73508775], shape=(50,), dtype=float32)
(50,)


### One-hot encoding

One-hot encoding, kategorik verileri sayısal verilere dönüştürmek için kullanılan bir işlemdir. Makine öğrenimi modelleri genellikle sayısal verilerle çalışırken, kategorik veriler (örneğin, renkler, kategoriler, etiketler vb.) doğrudan kullanılamaz. Bu nedenle, kategorik verileri sayısal biçime dönüştürmek için one-hot encoding yöntemi kullanılır.

One-hot encoding, her kategoriye ait bir sütun oluşturarak verileri temsil eder. Bir kategorinin varlığı durumunda ilgili sütuna 1 değeri atanırken, diğer sütunlara 0 değeri atanır. Bu şekilde, her örnek farklı kategorilere ait 1 ve geri kalan tüm sütunlarda 0 içeren bir vektör olarak temsil edilir.

Örnek olarak, "Renk" adında bir kategorik özniteliğiniz olduğunu ve üç renk seçeneğinizin (kırmızı, yeşil, mavi) olduğunu düşünelim. One-hot encoding ile bu renkleri temsil eden vektörler şu şekilde olabilir:

Kırmızı: [1, 0, 0]
Yeşil: [0, 1, 0]
Mavi: [0, 0, 1]

Bu yöntem, modelin kategorik verileri daha iyi anlamasını sağlar ve kategoriler arasındaki ilişkileri doğru bir şekilde yorumlamasına yardımcı olur.

In [57]:
data = {'Renk': ['Kırmızı', 'Yeşil', 'Mavi', 'Kırmızı']}
df = pd.DataFrame(data)

# One-hot encoding işlemi
encoded_df = pd.get_dummies(df, columns=['Renk'])
print(encoded_df)

   Renk_Kırmızı  Renk_Mavi  Renk_Yeşil
0          True      False       False
1         False      False        True
2         False       True       False
3          True      False       False


In [55]:
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# one-hot encode our list of indices
tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [59]:
# Örnek one hot encoding
tf.one_hot(some_list, depth=4, on_value="x", off_value=".")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'x', b'.', b'.', b'.'],
       [b'.', b'x', b'.', b'.'],
       [b'.', b'.', b'x', b'.'],
       [b'.', b'.', b'.', b'x']], dtype=object)>

### Squaring, log, square root

In [66]:
H = tf.range(1, 10)
print(H)

# Karesini alalım
print(tf.square(H))

# karekök alma
print(tf.math.sqrt(tf.cast(H, dtype=float)))

# logaritma
print(tf.math.log(tf.cast(H, dtype=float)))


tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor([ 1  4  9 16 25 36 49 64 81], shape=(9,), dtype=int32)
tf.Tensor(
[1.        1.4142135 1.7320508 2.        2.236068  2.4494898 2.6457512
 2.828427  3.       ], shape=(9,), dtype=float32)
tf.Tensor(
[0.        0.6931472 1.0986123 1.3862944 1.609438  1.7917595 1.9459102
 2.0794415 2.1972246], shape=(9,), dtype=float32)


### Tensors and NumPy

In [70]:
#numpy array kullanarak tensor oluşturmak
J = tf.constant(np.array([3., 7., 10.]))
print(J)

# Tensoru tekrar numpy array'e çevirmek
print(np.array(J))

tf.Tensor([ 3.  7. 10.], shape=(3,), dtype=float64)
[ 3.  7. 10.]
